# Generated by Django 3.2.14 on 2022-07-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwallet',
            name='client_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm.client'),
        ),
    ]
